name: Deploy Flask App

on:
  push:
    branches:
      - main

env:
  HEALTHCHECK_URL: http://shatla.app:50000  # Still available for other uses

jobs:
  Build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Virtual env
        run: |
          sudo apt install python3.12-venv -y
          python3 -m venv venv
          source venv/bin/activate
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Deploy Flask Application
        run: |
          nohup python3 main.py &
